service: transformer-function
provider:
  name: aws
  region: us-east-2
  timeout: 120

  environment:
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}

package:
  exclude:
    - Dockerfile
    - docker-compose.yml

functions:
  slack:
    runtime: python3.7
    handler: lambda_function.lambda_handler
    description: "Post message to Slack"
    timeout: 60 