service: kusoripu-function
provider:
  name: aws
  region: us-east-2
  timeout: 120
  vpc:
    securityGroupIds:
      - sg-0eff49c601074e8a4 
    subnetIds:
      - subnet-cd71aea6
      - subnet-a4b3cfe8
      - subnet-7f130705

  environment:
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}

package:
  exclude:
    - Dockerfile
    - docker-compose.yml

functions:
  transformer:
    runtime: python3.7
    handler: lambda_function.lambda_handler
    description: "対話モデルAPI"
    timeout: 60 
    environment:
       PYTHONPATH: "/mnt/lambda"
